services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: warehouse-management-app
        container_name: app
        restart: unless-stopped
        ports:
            - "9000:9000"
        environment:
            DB_HOST: db
            DB_PORT: 3306
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - warehouse-management-network
        depends_on:
            - db

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - warehouse-management-network
        depends_on:
            - app

    db:
        image: mysql
        container_name: db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: warehouseManageDB
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - warehouse-management-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "3400:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: password
        depends_on:
            - db

networks:
    warehouse-management-network:
        driver: bridge
